# Generated by Django 4.1.6 on 2023-04-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invitee_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('invitee_industry', models.CharField(max_length=50)),
                ('invitee_linkedin_url', models.CharField(max_length=50)),
                ('meeting_link', models.CharField(max_length=100)),
                ('meeting_notes', models.TextField()),
                ('questions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_start_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
