# Generated by Django 4.1.6 on 2023-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='invitee_industry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitee_linkedin_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitee_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
