# Generated by Django 4.1.6 on 2023-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_meeting_invitee_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
