# Generated by Django 4.1.6 on 2023-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_meeting_meeting_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='invitee_industry',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitee_linkedin_url',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitee_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_notes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='questions',
            field=models.TextField(default='', null=True),
        ),
    ]
