# Generated by Django 4.1.6 on 2023-04-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_meeting_invitee_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
