# Generated by Django 4.1.6 on 2023-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invitee_background',
            field=models.TextField(blank=True, default=''),
        ),
    ]
