# Generated by Django 4.1.6 on 2023-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_meeting_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='goal',
            field=models.TextField(blank=True, default=''),
        ),
    ]
