# Generated by Django 4.1.6 on 2023-08-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_experience_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['created_at']},
        ),
    ]
